DrugEncoder:
  model: 'RoBert'
  d_model : 256
  n_layer : 3
  n_head : 8
  attention : 'OriginMHA'
  activation : 'gelu'
  dropout : 0.1
  vocab_size : 2362

ProteinEncoder:
  d_model : 1280

InteractionDecoder:
  d_model: 256
  n_layer: 3
  n_head: 8
  attention: 'OriginMHA'
  activation: 'gelu'
  dropout : 0.1


use_llm: true
llm_hidden_size: 896
llm_model_path: "models\\LLM-Qwen\\snapshots\\91d2aff3f957f99e4c74c962f2f408dcc88a18d8"

lora_r: 8 #8
lora_alpha: 16 #16
lora_dropout: 0.1



